### ISSUE TITLE
Internal Error when running mockery

### ISSUE THREAD

**Issue by jtbonhomme** [vektra/mockery#343]
### Package version

* /usr/local/Cellar/mockery/2.4.0-beta/bin/mockery (installed from brew)
* go version go1.15.2 darwin/amd64
* macOS Catalina 10.15.6

### Issue

Interface source code from which I want to generate a mock:
```go
package controler

import (
	"github.com/google/uuid"
	"github.com/jtbonhomme/monorepo/books/models"
	"github.com/jtbonhomme/monorepo/books/storage"
)

type IControler interface {
	// Count returns total collection itemd number
	CountBooks(string, uuid.UUID) (int, error)
	// SelectAllBooks reads all records from storage. These records can be ordered, filtered, and paginated.
	SelectAllBooks([]string, int, int, string, uuid.UUID) ([]models.BookResponse, error)
	// SelectBookFromUUID reads a record from its UUID
	SelectBookFromUUID(uuid.UUID, uuid.UUID) (*models.BookResponse, error)
	// DeleteBook removes a record given its UUID
	DeleteBook(uuid.UUID, uuid.UUID) error
	// UpdateBook updates a record given its UUID
	UpdateBook(uuid.UUID, *models.BookUpdateRequest, uuid.UUID) (*models.BookResponse, error)
	// CreateBook creates a new record
	CreateBook(*models.BookCreateRequest, uuid.UUID) (*models.BookResponse, error)
	// Storage returns internal storage
	Storage() storage.IStorage
}
````

Command launched:
```sh
$ mockery -name=IControler
2020/11/11 18:01:43 internal error: nil Pkg importing "github.com/google/uuid" from "github.com/jtbonhomme/monorepo/books/controler"
```

Running with docker causes a similar issue:
```sh
$ docker run -v "$PWD":/src -w /src vektra/mockery --name=IControler

11 Nov 20 17:09 UTC INF Starting mockery dry-run=false version=2.4.0-beta
11 Nov 20 17:09 UTC INF Walking dry-run=false version=2.4.0-beta
11 Nov 20 17:09 UTC ERR Error parsing file error="/src/controler.go:4:2: could not import github.com/google/uuid (invalid package name: \"\")" dry-run=false version=2.4.0-beta
11 Nov 20 17:09 UTC ERR Error parsing file error="/src/controler.go:4:2: could not import github.com/google/uuid (invalid package name: \"\")" dry-run=false version=2.4.0-beta
11 Nov 20 17:09 UTC FTL Unable to find 'IControler' in any go files under this path dry-run=false version=2.4.0-beta
```

**Comment by LandonTClipp** [comment]
Does the same thing happen when you run under v2.3.0?

**Comment by jtbonhomme** [comment]
Hi Landon,

Yes it does:

```sh
$ docker run -v "$PWD":/src -w /src vektra/mockery:v2.3 --name=IControler

12 Nov 20 09:04 UTC INF Starting mockery dry-run=false version=2.3.0
12 Nov 20 09:04 UTC INF Walking dry-run=false version=2.3.0
12 Nov 20 09:04 UTC ERR Error parsing file error="/src/controler.go:4:2: could not import github.com/google/uuid (invalid package name: \"\")" dry-run=false version=2.3.0
12 Nov 20 09:04 UTC ERR Error parsing file error="/src/controler.go:4:2: could not import github.com/google/uuid (invalid package name: \"\")" dry-run=false version=2.3.0
12 Nov 20 09:04 UTC FTL Unable to find 'IControler' in any go files under this path dry-run=false version=2.3.0
```

**Comment by jtbonhomme** [comment]
Landon,

I installed mockery with the `go get` command, and it worked:

```sh
$ go get -u github.com/vektra/mockery/v2/.../
...
$ mockery --name=IControler

12 Nov 20 10:07 CET INF Starting mockery dry-run=false version=0.0.0-dev
12 Nov 20 10:07 CET INF Walking dry-run=false version=0.0.0-dev
12 Nov 20 10:07 CET INF Generating mock dry-run=false interface=IControler qualified-name=github.com/jtbonhomme/monorepo/books/controler version=0.0.0-dev
```

**Comment by jtbonhomme** [comment]
And calling directly the brew installed binary worked too:

```sh
$ /usr/local/Cellar/mockery/2.4.0-beta/bin/mockery --name=IControler
12 Nov 20 10:08 CET INF Starting mockery dry-run=false version=2.4.0-beta
12 Nov 20 10:08 CET INF Walking dry-run=false version=2.4.0-beta
12 Nov 20 10:08 CET INF Generating mock dry-run=false interface=IControler qualified-name=github.com/jtbonhomme/monorepo/books/controler version=2.4.0-beta
```

I think my first attempt executed an old version of mockery I installed months ago. May be there is still an issue with docker way to run it, but it is not a big deal for me.

Thank you for your help,

**Comment by TSFenwick** [comment]
@LandonTClipp I'm seeing the same error on 2.3 and 2.4 when i'm in a subdirectory or package that isn't main.

```
docker run -v "$PWD":/src -w /src vektra/mockery:v2.3 --all --recursive=true  --keeptree
13 Nov 20 02:00 UTC INF Starting mockery dry-run=false version=2.3.0
13 Nov 20 02:00 UTC INF Walking dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="/src/mocks/Service.go:8:9: could not import gitlab.com/banyan-security/common (invalid package name: \"\")" dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="/src/oauth_cache.go:6:7: could not import github.com/ccpaging/log4go (invalid package name: \"\")" dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="/src/oauth_cache.go:6:7: could not import github.com/ccpaging/log4go (invalid package name: \"\")" dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="/src/oauth_cache.go:6:7: could not import github.com/ccpaging/log4go (invalid package name: \"\")" dry-run=false version=2.3.0
```
and when i run it at the root of the project i see this
```
ocker run -v "$PWD":/src -w /src vektra/mockery:v2.3 --all --recursive=true  --keeptree
13 Nov 20 02:00 UTC INF Starting mockery dry-run=false version=2.3.0
13 Nov 20 02:00 UTC INF Walking dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="err: exit status 1: stderr: go: github.com/dexidp/dex@v0.0.0-20191003094918-4bede5eb8082: git init --bare in /go/pkg/mod/cache/vcs/59fe64852e601261eed9ad427ae15e5802c96273f25d89946e167868cc100357: exec: \"git\": executable file not found in $PATH\n" dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="err: exit status 1: stderr: go: github.com/dexidp/dex@v0.0.0-20191003094918-4bede5eb8082: git init --bare in /go/pkg/mod/cache/vcs/59fe64852e601261eed9ad427ae15e5802c96273f25d89946e167868cc100357: exec: \"git\": executable file not found in $PATH\n" dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="err: exit status 1: stderr: go: github.com/dexidp/dex@v0.0.0-20191003094918-4bede5eb8082: git init --bare in /go/pkg/mod/cache/vcs/59fe64852e601261eed9ad427ae15e5802c96273f25d89946e167868cc100357: exec: \"git\": executable file not found in $PATH\n" dry-run=false version=2.3.0
13 Nov 20 02:00 UTC ERR Error parsing file error="err: exit status 1: stderr: go: github.com/dexidp/dex@v0.0.0-20191003094918-4bede5eb8082: git init --bare in /go/pkg/mod/cache/vcs/59fe64852e601261eed9ad427ae15e5802c96273f25d89946e167868cc100357: exec: \"git\": executable file not found in $PATH\n" dry-run=false version=2.3.0
...
ctrl-c
```
I am able to get it to work fine with homebrew version, but would like to have this working via docker.

How can i start getting some more debugging info for this issue?

Thanks

**Comment by mkfsn** [comment]
I have the same issue using mockery@v0.0.0-20181123154057-e78b021dcbb5.

It seems to me that mockery doesn't work well with go 1.14 and 1.15, but with go 1.13 I have no problem.

**Comment by LandonTClipp** [comment]
Hi folks, thanks for the reports. I am taking a look at this problem now. If anyone happens to find what the issue is, please feel free to submit a PR and we can get this fixed. I'll let you know if I find anything.

**Comment by LandonTClipp** [comment]
@jtbonhomme I am not able to debug this further because it seems that `github.com/jtbonhomme/monorepo/books/models` either doesn't exist or it's a private repo. The issue seems to be when `mockery` calls out to the following

```
[ltclipp@landon-virtualbox test]$ go build github.com/jtbonhomme/monorepo/books/models
go: finding module for package github.com/jtbonhomme/monorepo/books/models
cannot find module providing package github.com/jtbonhomme/monorepo/books/models: module github.com/jtbonhomme/monorepo/books/models: git ls-remote -q origin in /home/ltclipp/go/pkg/mod/cache/vcs/8c6995376b252e3f3610d54ee604fcb541ded781828340fb241a3851a1ec7fcd: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

I think your issue might be that mockery cannot read the private repo. The error message is not super informative, however I don't think there's much we can do since that's what `package.Load` returns.

**Comment by malyusha** [comment]
Got the same problem as TS. Fixed it by:
1. `go mod vendor` to vendor all the dependencies
2. then run docker with project directory mounted volume;
3. then you can remove vendor directory.

```
echo "Vendoring all deps"
go mod vendor
docker run 
echo "Generating mocks"
docker run --rm -v "$PWD:/src" -w "/src" vektra/mockery:v2.4 --name.....
# This is optional, you may keep the directory if your team is using vendoring by default
echo "Removing vendor"
rm -rf vendor
```
