### ISSUE TITLE
g.iface.NamedType.TypeParams undefined (type *types.Named has no field or method TypeParams)

### ISSUE THREAD

**Issue by euskadi31** [vektra/mockery#478]
Description
-------------
Code:

```go
//go:generate go run -mod=mod github.com/vektra/mockery/v2 --inpackage --case underscore --name=Client
type Client interface {...}
```

Logs:
``` 
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:75:33: g.iface.NamedType.TypeParams undefined (type *types.Named has no field or method TypeParams)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:82:31: g.iface.NamedType.TypeArgs undefined (type *types.Named has no field or method TypeArgs)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:271:25: g.iface.NamedType.TypeParams undefined (type *types.Named has no field or method TypeParams)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:287:25: g.iface.NamedType.TypeParams undefined (type *types.Named has no field or method TypeParams)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:403:7: t.TypeArgs undefined (type *types.Named has no field or method TypeArgs)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:406:30: t.TypeArgs undefined (type *types.Named has no field or method TypeArgs)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:407:[20](https://github.com/angell-bike/angell-services/runs/6877143488?check_suite_focus=true#step:6:21): t.TypeArgs undefined (type *types.Named has no field or method TypeArgs)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:408:12: t.TypeArgs undefined (type *types.Named has no field or method TypeArgs)
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:412:8: undefined: types.TypeParam
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:491:8: undefined: types.Union
Error: /home/runner/go/pkg/mod/github.com/vektra/mockery/v2@v2.13.0/pkg/generator.go:491:8: too many errors
```

Version
--------

v2.13.0

Steps to Reproduce
------------------

1. go generate

**Comment by LandonTClipp** [comment]
Hi what version of golang are you using? How did you install mockey?

**Comment by euskadi31** [comment]
Use the latest version 1.18.3

**Comment by LandonTClipp** [comment]
Can you please purge your local golang cache and rebuild using 1.18.

**Comment by LandonTClipp** [comment]
I haven't had any reports of this recurring, so I will close this out.
